//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaneProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int Id { get; set; }
        public string LocationFrom { get; set; }
        public string LocationTo { get; set; }
        public Nullable<System.DateTime> TimeOfFlight { get; set; }
        public Nullable<System.DateTime> TimeOfArrival { get; set; }
        public string TypeOfPlane { get; set; }
        public string UniqueNumberOfPlane { get; set; }
        public string NamePilot { get; set; }
        public Nullable<int> CapacityOfPassengers { get; set; }
        public Nullable<int> CapacityBusinessClass { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
